extends Node
## Textos do jogo em português (padrão) e inglês.
## Uso: Loc.t("menu.play") ou Loc.t("hud.reward", [350]) com "{0}" no texto.

const LANGUAGES := ["pt", "en"]

var language := "pt"

var _tables := {
	"pt": {},
	"en": {},
}


func _ready() -> void:
	_load_tables()
	var system := OS.get_locale_language()
	language = "pt" if system == "pt" else "en"


func set_language(code: String) -> void:
	if code == "" or not LANGUAGES.has(code):
		var system := OS.get_locale_language()
		code = "pt" if system == "pt" else "en"
	if code != language:
		language = code
		Bus.language_changed.emit()


func t(key: String, args: Array = []) -> String:
	var table: Dictionary = _tables.get(language, {})
	var text: String = table.get(key, _tables["pt"].get(key, key))
	if args.is_empty():
		return text
	return text.format(args)


func _add(key: String, pt: String, en: String) -> void:
	_tables["pt"][key] = pt
	_tables["en"][key] = en


func _load_tables() -> void:
	# Menu principal
	_add("menu.continue", "CONTINUAR", "CONTINUE")
	_add("menu.new_game", "NOVO JOGO", "NEW GAME")
	_add("menu.settings", "OPÇÕES", "SETTINGS")
	_add("menu.credits", "CRÉDITOS", "CREDITS")
	_add("menu.quit", "SAIR", "QUIT")
	_add("menu.tagline", "Entregas contra o relógio numa cidade que não para.", "Race the clock through a city that never stops.")
	_add("menu.new_game_confirm", "Começar um jogo novo apaga o progresso atual. Continuar?", "Starting a new game erases your current progress. Continue?")
	_add("menu.yes", "SIM", "YES")
	_add("menu.no", "NÃO", "NO")
	_add("menu.back", "VOLTAR", "BACK")
	_add("menu.loading", "Construindo a cidade...", "Building the city...")
	_add("menu.credits_text", "Um jogo feito com Godot Engine 4.\nTodo o visual e o som são gerados por código.\nFontes: veja CREDITS.md.", "A game made with Godot Engine 4.\nAll visuals and sound are generated by code.\nFonts: see CREDITS.md.")

	# Pausa
	_add("pause.title", "PAUSADO", "PAUSED")
	_add("pause.resume", "CONTINUAR", "RESUME")
	_add("pause.settings", "OPÇÕES", "SETTINGS")
	_add("pause.garage", "GARAGEM", "GARAGE")
	_add("pause.main_menu", "MENU PRINCIPAL", "MAIN MENU")
	_add("pause.quit", "SALVAR E SAIR", "SAVE & QUIT")

	# Opções
	_add("settings.title", "OPÇÕES", "SETTINGS")
	_add("settings.graphics", "Qualidade gráfica", "Graphics quality")
	_add("settings.quality.low", "Baixa", "Low")
	_add("settings.quality.medium", "Média", "Medium")
	_add("settings.quality.high", "Alta", "High")
	_add("settings.quality.ultra", "Ultra", "Ultra")
	_add("settings.fullscreen", "Tela cheia", "Fullscreen")
	_add("settings.vsync", "V-Sync", "V-Sync")
	_add("settings.render_scale", "Escala de renderização", "Render scale")
	_add("settings.master", "Volume geral", "Master volume")
	_add("settings.sfx", "Efeitos", "Effects")
	_add("settings.engine", "Motor", "Engine")
	_add("settings.ambient", "Ambiente", "Ambience")
	_add("settings.language", "Idioma", "Language")
	_add("settings.units", "Velocidade", "Speed units")
	_add("settings.traffic", "Trânsito", "Traffic")
	_add("settings.sensitivity", "Sensibilidade da câmera", "Camera sensitivity")
	_add("settings.invert_y", "Inverter câmera (vertical)", "Invert camera (vertical)")
	_add("settings.auto", "Automático", "Automatic")
	_add("settings.controls", "Controles", "Controls")
	_add("settings.controls_text",
		"W/S acelerar e frear (segure S parado para dar ré) • A/D virar • Espaço freio de mão\nE abastecer/garagem • R resgatar • Tab celular • M mapa • C câmera • L faróis • H buzina • Esc pausa\nBotão direito do mouse: olhar em volta\nControle: RT/LT acelerar/frear • analógico virar • A freio de mão • X abastecer • Y câmera • Select celular",
		"W/S throttle and brake (hold S when stopped to reverse) • A/D steer • Space handbrake\nE refuel/garage • R recover • Tab phone • M map • C camera • L headlights • H horn • Esc pause\nRight mouse button: look around\nGamepad: RT/LT throttle/brake • stick steer • A handbrake • X refuel • Y camera • Select phone")

	# HUD
	_add("hud.no_delivery", "📦 PROCURAR ENTREGA — abra o celular [Tab]", "📦 FIND A DELIVERY — open your phone [Tab]")
	_add("hud.go_pickup", "📍 VÁ ATÉ A COLETA", "📍 GO TO PICKUP")
	_add("hud.delivering", "📦 ENTREGA ATIVA", "📦 DELIVERY ACTIVE")
	_add("hud.late", "❌ ENTREGA ATRASADA", "❌ DELIVERY LATE")
	_add("hud.pickup_at", "Coleta: {0}", "Pickup: {0}")
	_add("hud.deliver_to", "Destino: {0}", "Deliver to: {0}")
	_add("hud.timer_starts", "O tempo começa na coleta", "The clock starts at pickup")
	_add("hud.cargo", "Carga", "Cargo")
	_add("hud.fuel", "Combustível", "Fuel")
	_add("hud.stop_to_load", "Pare na vaga para carregar", "Stop in the bay to load")
	_add("hud.stop_to_unload", "Pare na vaga para entregar", "Stop in the bay to deliver")
	_add("hud.loading", "Carregando...", "Loading...")
	_add("hud.unloading", "Entregando...", "Delivering...")
	_add("hud.refueling", "Abastecendo... {0}", "Refueling... {0}")
	_add("hud.late_bonus", "Entregue em {0} para ainda ganhar {1}", "Deliver within {0} to still earn {1}")
	_add("hud.bonus_fast", "⚡ No ritmo do bônus!", "⚡ On pace for the bonus!")
	_add("hud.hurry", "Corre!", "Hurry!")
	_add("hud.gear", "Marcha", "Gear")
	_add("hud.out_of_fuel", "⛽ Sem combustível! Aperte R para chamar o guincho.", "⛽ Out of fuel! Press R to call a tow truck.")

	# Celular
	_add("phone.app_name", "EntregaJá", "EntregaJá")
	_add("phone.new_orders", "Novos pedidos", "New orders")
	_add("phone.accept", "ACEITAR", "ACCEPT")
	_add("phone.refresh", "Atualizar pedidos", "Refresh orders")
	_add("phone.refresh_wait", "Atualizar ({0}s)", "Refresh ({0}s)")
	_add("phone.pickup", "Coleta", "Pickup")
	_add("phone.dropoff", "Entrega", "Drop-off")
	_add("phone.route", "Rota", "Route")
	_add("phone.time", "Prazo", "Time")
	_add("phone.from_you", "{0} de você", "{0} from you")
	_add("phone.active", "Entrega em andamento", "Delivery in progress")
	_add("phone.cancel", "Cancelar entrega", "Cancel delivery")
	_add("phone.needs_vehicle", "Precisa de: {0}", "Requires: {0}")
	_add("phone.too_big", "Não cabe no seu veículo", "Doesn't fit your vehicle")
	_add("phone.hint", "1, 2, 3 aceitam • Tab fecha", "1, 2, 3 accept • Tab closes")
	_add("phone.balance", "Saldo", "Balance")
	_add("phone.rating", "Avaliação", "Rating")

	# Resultado
	_add("result.done", "✅ ENTREGA CONCLUÍDA!", "✅ DELIVERY COMPLETE!")
	_add("result.done_late", "✅ ENTREGUE COM ATRASO", "✅ DELIVERED LATE")
	_add("result.failed", "❌ ENTREGA ATRASADA", "❌ DELIVERY FAILED")
	_add("result.failed_text", "O prazo acabou e o pedido foi cancelado. Você não perdeu dinheiro.", "Time ran out and the order was cancelled. You didn't lose any money.")
	_add("result.base", "Entrega", "Delivery")
	_add("result.bonus", "Bônus de rapidez", "Speed bonus")
	_add("result.tip", "Gorjeta", "Tip")
	_add("result.damage", "Carga danificada", "Damaged cargo")
	_add("result.total", "Total", "Total")
	_add("result.condition", "Estado da carga: {0}%", "Cargo condition: {0}%")

	# Notificações
	_add("toast.picked_up", "📦 Encomenda carregada! Leve até {0}.", "📦 Cargo loaded! Take it to {0}.")
	_add("toast.cancelled", "Entrega cancelada.", "Delivery cancelled.")
	_add("toast.saved", "💾 Jogo salvo", "💾 Game saved")
	_add("toast.save_failed", "⚠️ Não foi possível salvar o jogo!", "⚠️ Could not save the game!")
	_add("toast.fine_red_light", "📸 Multa: avançou o sinal vermelho (-{0})", "📸 Fine: ran a red light (-{0})")
	_add("toast.recovered", "🔄 Veículo resgatado", "🔄 Vehicle recovered")
	_add("toast.tow", "🚛 Guincho: veículo levado ao posto (-{0})", "🚛 Tow truck: vehicle taken to a gas station (-{0})")
	_add("toast.refueled", "⛽ Tanque cheio (-{0})", "⛽ Tank full (-{0})")
	_add("toast.no_money_fuel", "💸 Dinheiro insuficiente para abastecer", "💸 Not enough money for fuel")
	_add("toast.late", "⏰ O prazo acabou! Ainda dá para entregar por menos.", "⏰ Time's up! You can still deliver for less.")
	_add("toast.cargo_hit", "💥 Cuidado com a carga! ({0}%)", "💥 Careful with the cargo! ({0}%)")
	_add("toast.too_big", "Esse pedido não cabe no seu veículo.", "That order doesn't fit your vehicle.")

	# Eventos
	_add("event.accident", "🚧 ACIDENTE na {0}! Rua bloqueada — procure outro caminho.", "🚧 ACCIDENT on {0}! Road blocked — find another way.")
	_add("event.accident_end", "✅ {0} foi liberada.", "✅ {0} is open again.")
	_add("event.storm", "🌧️ TEMPESTADE! Pista molhada: freie antes.", "🌧️ STORM! Wet roads: brake earlier.")
	_add("event.storm_end", "☀️ A chuva passou.", "☀️ The rain has passed.")
	_add("event.shortcut", "🔓 ATALHO LIBERADO: {0} por {1}s!", "🔓 SHORTCUT OPEN: {0} for {1}s!")
	_add("event.shortcut_closing", "⏳ O atalho fecha em 10 segundos!", "⏳ Shortcut closes in 10 seconds!")
	_add("event.shortcut_end", "🔒 O atalho fechou.", "🔒 The shortcut has closed.")

	# Garagem
	_add("garage.title", "GARAGEM", "GARAGE")
	_add("garage.buy", "COMPRAR {0}", "BUY {0}")
	_add("garage.use", "USAR", "USE")
	_add("garage.in_use", "EM USO", "IN USE")
	_add("garage.bought", "🚗 {0} é seu!", "🚗 {0} is yours!")
	_add("garage.no_money", "💸 Falta dinheiro", "💸 Not enough money")
	_add("garage.speed", "Velocidade", "Top speed")
	_add("garage.accel", "Aceleração", "Acceleration")
	_add("garage.handling", "Dirigibilidade", "Handling")
	_add("garage.cargo", "Carga", "Cargo")
	_add("garage.only_at_hq", "A garagem fica na Central de Entregas.", "The garage is at the Delivery HQ.")

	_add("garage.finish_delivery", "Termine a entrega antes de trocar de veículo.", "Finish the delivery before switching vehicles.")
	_add("garage.close", "FECHAR", "CLOSE")
	_add("garage.cargo_size", "Carga máx.: {0}", "Max cargo: {0}")

	# Serviços e avisos extras
	_add("hud.refuel_hold", "Segure E para abastecer (R$ {0}/L)", "Hold E to refuel ($ {0}/L)")
	_add("hud.tank_full", "Tanque cheio", "Tank full")
	_add("hud.garage_hint", "E: abrir a garagem", "E: open the garage")
	_add("hud.flipped", "Veículo virado — aperte R para resgatar", "Vehicle flipped — press R to recover")
	_add("hud.low_fuel", "⛽ Pouco combustível! Procure um posto (ícone ⛽ no mapa).", "⛽ Low fuel! Find a gas station (⛽ on the map).")
	_add("hud.distance", "{0} até o destino", "{0} to go")
	_add("hud.money", "R$ {0}", "$ {0}")
	_add("hud.time_left", "Tempo", "Time")
	_add("hud.event", "Evento", "Event")
	_add("hud.map_title", "MAPA — M fecha", "MAP — M closes")
	_add("hud.legend", "📦 coleta  🏁 destino  ⛽ posto  🏠 central", "📦 pickup  🏁 destination  ⛽ gas  🏠 HQ")
	_add("toast.welcome", "Bem-vindo à EntregaJá! Abra o celular [Tab] e aceite sua primeira entrega.", "Welcome to EntregaJá! Open your phone [Tab] and accept your first delivery.")
	_add("result.continue", "Novos pedidos no celular [Tab]", "New orders on your phone [Tab]")
	_add("phone.empty", "Nenhum pedido agora. Atualize em instantes.", "No orders right now. Refresh in a moment.")
	_add("phone.no_offer_active", "Termine a entrega atual para aceitar outra.", "Finish your current delivery to accept another.")
	_add("phone.minutes", "{0} min {1} s", "{0} min {1} s")
	_add("menu.saving", "Salvando...", "Saving...")
	_add("settings.apply", "APLICAR", "APPLY")
	_add("settings.units.metric", "km/h", "km/h")
	_add("settings.units.imperial", "mph", "mph")
	_add("settings.lang.auto", "Automático", "Automatic")
	_add("settings.lang.pt", "Português", "Portuguese")
	_add("settings.lang.en", "Inglês", "English")
	_add("settings.traffic.low", "Pouco", "Light")
	_add("settings.traffic.normal", "Normal", "Normal")
	_add("settings.traffic.high", "Muito", "Heavy")

	# Tamanhos de carga
	_add("cargo.S", "Pequena", "Small")
	_add("cargo.M", "Média", "Medium")
	_add("cargo.L", "Grande", "Large")
