import { SectorConfig, SectorId } from "./types";

export const SECTORS: Record<SectorId, SectorConfig> = {
  saas: {
    id: "saas",
    name: "SaaS B2B",
    emoji: "💻",
    tagline: "Assinatura mensal para empresas. Margem alta, venda mais lenta.",
    referencePrice: 190,
    unitCost: 18,
    fixedCosts: 3200,
    marketSize: 14000,
    marketGrowth: 0.015,
    churnBase: 0.035,
    cacBase: 140,
    salaries: { sales: 4200, support: 3100, product: 5400 },
  },
  ecommerce: {
    id: "ecommerce",
    name: "E-commerce",
    emoji: "📦",
    tagline: "Venda direta ao consumidor. Volume alto, margem apertada.",
    referencePrice: 65,
    unitCost: 34,
    fixedCosts: 2600,
    marketSize: 60000,
    marketGrowth: 0.02,
    churnBase: 0.12,
    cacBase: 32,
    salaries: { sales: 3400, support: 2600, product: 4200 },
  },
  food: {
    id: "food",
    name: "Food Service",
    emoji: "🍔",
    tagline: "Assinatura de refeições/insumos. Fidelidade local, logística pesada.",
    referencePrice: 39,
    unitCost: 21,
    fixedCosts: 4100,
    marketSize: 22000,
    marketGrowth: 0.008,
    churnBase: 0.09,
    cacBase: 24,
    salaries: { sales: 3000, support: 2400, product: 3600 },
  },
  servicos: {
    id: "servicos",
    name: "Serviços Profissionais",
    emoji: "🧑‍💼",
    tagline: "Consultoria/assinatura de serviço especializado. Relacionamento importa.",
    referencePrice: 320,
    unitCost: 40,
    fixedCosts: 2200,
    marketSize: 5000,
    marketGrowth: 0.01,
    churnBase: 0.05,
    cacBase: 260,
    salaries: { sales: 4800, support: 3400, product: 4600 },
  },
};

export const SECTOR_LIST = Object.values(SECTORS);
